AppMvc/Models/Store.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppMvc.Models
{
    public class Store
    {
        [Key]
        public int StoreId {get; set;}
        [Required(ErrorMessage = "Campo obrigatório")]
        public string? Name {get; set;}
        [Required(ErrorMessage = "Campo obrigatório")]
        public string? CNPJ {get; set;}
   
        [Required(ErrorMessage = "Campo obrigatório")]
        public string? Telefone {get; set;}
        [Required(ErrorMessage = "Campo obrigatório")]
        public List<Iphone>? IphoneList { get; set; } 

        public Iphone? Iphone { get; set; }
        
    }
}

AppMvc/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppMvc.Data;
using AppMvc.Models;
using Microsoft.Build.Framework;
using Mono.TextTemplating;
using static System.Formats.Asn1.AsnWriter;
using System.Collections;
using System.Net;

namespace AppMvc.Controllers
{
    public class StoreController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StoreController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Store
        public async Task<IActionResult> Index()
        {
            return View(await _context.Stores.ToListAsync());
        }

        // GET: Store/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores
                .FirstOrDefaultAsync(m => m.StoreId == id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // GET: Store/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Store/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StoreId, Name,CNPJ,Telefone,IphoneList, Iphone")] Store store)
        {
            if (ModelState.IsValid)
            {
                if(store.IphoneList != null)
                {
                   
                   store.IphoneList.Add(store.Iphone);
                    
                }
                _context.Stores.Add(store);
                
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
                
            }
            return View(store);
        }

        // GET: Store/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores.FindAsync(id);

            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StoreId,Name,CNPJ,Telefone, IphoneList")] Store store)
        {
            if (id != store.StoreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(store);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoreExists(store.StoreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(store);
        }

        // GET: Store/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores
                .FirstOrDefaultAsync(m => m.StoreId == id);

            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // POST: Store/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var store = await _context.Stores.FindAsync(id);
            if (store != null)
            {
                _context.Stores.Remove(store);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home" );
        }

        
        private bool StoreExists(int id)
        {
            return _context.Stores.Any(e => e.StoreId == id);
        }
    }
}

AppMvc/Views/Store/Create.cshtml
@model AppMvc.Models.Store

@{
    ViewData["Title"] = "Create";
}

<h1>Criar: </h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CNPJ" class="control-label"></label>
                <input asp-for="CNPJ" class="form-control" />
                <span asp-validation-for="CNPJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Iphone.Model" class="control-label">Modelo:</label>
                <input asp-for="Iphone.Model" class="form-control" />
                <span asp-validation-for="Iphone.Model" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Iphone.ImagemUpload" class="control-label"></label>
                <input type="file" asp-for="Iphone.ImagemUpload" id="ImageUpload" class="form-control" />
                <span asp-validation-for="Iphone.ImagemUpload" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Iphone.Price" class="control-label">Preço</label>
                <input asp-for="Iphone.Price" class="form-control" />
                <span asp-validation-for="Iphone.Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $("#ImageUpload").attr("data-val", "true")
        $("#ImageUpload").attr("data-val-required", "Preencha o campo Imagem ");
    </script>

}

AppMvc/Views/Store/Delete.cshtml
@model AppMvc.Models.Store

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Store</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CNPJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CNPJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StoreId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Store" asp-action="Index">Back to List</a>
    </form>
</div>

AppMvc/Views/Store/Details.cshtml
@model AppMvc.Models.Store

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Store</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CNPJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CNPJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.StoreId">Edit</a> |
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

AppMvc/Views/Store/Edit.cshtml
@model AppMvc.Models.Store
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Store</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Store" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StoreId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nome</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CNPJ" class="control-label">CNPJ</label>
                <input asp-for="CNPJ" class="form-control" />
                <span asp-validation-for="CNPJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label">Telefone</label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <h4>IPhones da Loja : </h4>
            <hr/>
            
                @if(Model.IphoneList != null)
                {
                    @for(var i = 0; i < Model.IphoneList.Count; i++)
                    {
                        @if(Model.IphoneList[i] is not null)
                        {
                            <div class="form-group">
                                <label asp-for="IphoneList[i].Model" class="control-label">Modelo:</label>
                                <input asp-for="IphoneList[i].Model" class="form-control" />
                                <span asp-validation-for="IphoneList[i].Model" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Iphone.ImagemUpload" class="control-label"></label>
                                <input type="file" asp-for="Iphone.ImagemUpload" class="form-control"/>
                                <span asp-validation-for="Iphone.ImagemUpload" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Iphone.Price" class="control-label">Preço</label>
                                <input asp-for="Iphone.Price" class="form-control" />
                                <span asp-validation-for="Iphone.Price" class="text-danger"></span>
                            </div>
                        }
                        
                    }
                }
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}