AppMvc/Models/Iphone.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppMvc.Models
{
    public class Iphone
    {
        [Key]
        public int Id {get; set;}

        [Required(ErrorMessage = "Campo obrigatório")]
        public string? Model {get; set;}

        [Required(ErrorMessage = "Campo obrigatório")]
        [NotMapped]
        [DisplayName("ImagemProduto")]
        public IFormFile? ImagemUpload {get; set;}

        public string? Imagem {get; set;}
        
        [Required(ErrorMessage = "Campo obrigatório")]
        public double? Price {get; set;}
    }
}

AppMvc/Controllers/IphoneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppMvc.Data;
using AppMvc.Models;

namespace AppMvc.Controllers
{
    public class IphoneController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IphoneController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Iphone
        public async Task<IActionResult> Index()
        {
            return View(await _context.Iphones.ToListAsync());
        }

        // GET: Iphone/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var iphone = await _context.Iphones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (iphone == null)
            {
                return NotFound();
            }

            return View(iphone);
        }

        // GET: Iphone/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Iphone/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Model,ImagemUpload,Price")] Iphone iphone)
        {
            if (ModelState.IsValid)
            {
                var imgPrefixo = Guid.NewGuid() + "_";

                if (!await UploadImage(iphone.ImagemUpload, imgPrefixo)){
                    return View(iphone);
                }
                // Inicializa a lista de iPhones se for nula
                iphone.Imagem = imgPrefixo + iphone.ImagemUpload;

                _context.Add(iphone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(iphone);
        }

        // GET: Iphone/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var iphone = await _context.Iphones.FindAsync(id);
            if (iphone == null)
            {
                return NotFound();
            }
            return View(iphone);
        }

        // POST: Iphone/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Model,ImagemUpload,Price")] Iphone iphone)
        {
            if (id != iphone.Id)
            {
                return NotFound();
            }

            var iphonedb = await _context.Iphones.AsNoTracking().FirstOrDefaultAsync(i => i.Id == id);

            if (ModelState.IsValid)
            {
                try
                {
                    iphone.Imagem = iphonedb.Imagem;
                    if(iphone.ImagemUpload != null)
                    {
                        var imgPrefixo = Guid.NewGuid() + "_";
                        if(!await UploadImage(iphone.ImagemUpload, imgPrefixo))
                        {
                            return View(iphone);
                        }
                        iphone.Imagem = imgPrefixo + iphone.ImagemUpload.FileName;
                    }
                    _context.Update(iphone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IphoneExists(iphone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(iphone);
        }

        // GET: Iphone/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var iphone = await _context.Iphones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (iphone == null)
            {
                return NotFound();
            }

            return View(iphone);
        }

        // POST: Iphone/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var iphone = await _context.Iphones.FindAsync(id);
            if (iphone != null)
            {
                _context.Iphones.Remove(iphone);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<bool> UploadImage(IFormFile arquivo, string imgPrefixo)
        {
            if (arquivo.Length <= 0) return false;
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/image", imgPrefixo = arquivo.FileName);

            if (System.IO.File.Exists(path))
            {
                ModelState.AddModelError(string.Empty, "Já existe um arquivo com este nome !");
                return false;
            }

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await arquivo.CopyToAsync(stream);
            }
            return true;
        }


        private bool IphoneExists(int id)
        {
            return _context.Iphones.Any(e => e.Id == id);
        }
    }
}

AppMvc/Views/Iphone/Create.cshtml
@model AppMvc.Models.Iphone


@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Iphone</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagemUpload" class="control-label"></label>
                <input type="file" asp-for="ImagemUpload" class="form-control" />
                <span asp-validation-for="ImagemUpload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <button id="button" >Add</button>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a  asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppMvc/Views/Iphone/Delete.cshtml
@model AppMvc.Models.Iphone

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Iphone</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppMvc/Views/Iphone/Details.cshtml
@model AppMvc.Models.Iphone

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Iphone</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Iphone" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

AppMvc/Views/Iphone/Edit.cshtml
@model AppMvc.Models.Iphone

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Iphone</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppMvc/Views/Iphone/Index.cshtml
@model IEnumerable<AppMvc.Models.Iphone>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>